// This file will be generated by the IDL compiler in the future.
#ifndef IDL_TEST_I1_FACTORY_H_
#define IDL_TEST_I1_FACTORY_H_

#include "Test_I1.h"

namespace Test {

class I1_factory;
typedef CORBA::Nirvana::I_ptr <I1_factory> I1_factory_ptr;
typedef CORBA::Nirvana::I_var <I1_factory> I1_factory_var;
typedef CORBA::Nirvana::I_out <I1_factory> I1_factory_out;

extern const ::Nirvana::ImportInterfaceT <::CORBA::TypeCode> _tc_I1_factory;

}

namespace CORBA {
namespace Nirvana {

BRIDGE_BEGIN (::Test::I1_factory, "IDL:Test/I1_factory:1.0")
BASE_STRUCT_ENTRY (CORBA::Object, CORBA_Object)
BRIDGE_EPV
Interface* (*create)(Bridge < ::Test::I1_factory>*, Long, Interface*);
BRIDGE_END ()

template <class T>
class Client <T, ::Test::I1_factory> :
	public T
{
public:
	::Test::I1_var create (Long addendum);
};

template <class T>
::Test::I1_var Client <T, ::Test::I1_factory>::create (Long addendum)
{
	Environment _env;
	Bridge < ::Test::I1_factory>& _b (T::_get_bridge (_env));
	I_ret < ::Test::I1> _ret = (_b._epv ().epv.create) (&_b, addendum, &_env);
	_env.check ();
	return _ret;
}

}
}

namespace Test {

class I1_factory : public CORBA::Nirvana::ClientInterface <I1_factory, ::CORBA::Object>
{};

}

#endif
