// Contains imports for all objects declared in the "Test_I1_factory.h" header.
// This file will be generated by the IDL compiler in the future.
#include "Test_I1_factory.h"
#include <Nirvana/OLF.h>

namespace Test {

NIRVANA_OLF_SECTION extern const ::Nirvana::ImportInterfaceT <::CORBA::TypeCode>
_tc_I1_factory = { ::Nirvana::OLF_IMPORT_INTERFACE, I1_factory::repository_id_, ::CORBA::TypeCode::repository_id_ };

}
