// Contains imports for all objects declared in the "Test_I2.h" header.
// This file will be generated by the IDL compiler in the future.
#include "Test_I2.h"
#include <Nirvana/OLF.h>

namespace Test {

NIRVANA_OLF_SECTION extern const ::Nirvana::ImportInterfaceT <::CORBA::TypeCode>
_tc_I2 = { ::Nirvana::OLF_IMPORT_INTERFACE, I2::repository_id_, ::CORBA::TypeCode::repository_id_ };

}
