// This file will be generated by the IDL compiler in the future.
#ifndef IDL_TEST_I3_FACTORY_H_
#define IDL_TEST_I3_FACTORY_H_

#include "Test_I3.h"

namespace Test {

class I3_factory;
typedef CORBA::Nirvana::I_ptr <I3_factory> I3_factory_ptr;
typedef CORBA::Nirvana::I_var <I3_factory> I3_factory_var;
typedef CORBA::Nirvana::I_out <I3_factory> I3_factory_out;

extern const ::Nirvana::ImportInterfaceT <::CORBA::TypeCode> _tc_I3_factory;

}

namespace CORBA {
namespace Nirvana {

BRIDGE_BEGIN (::Test::I3_factory, "IDL:Test/I3_factory:1.0")
BASE_STRUCT_ENTRY (CORBA::Object, CORBA_Object)
BRIDGE_EPV
Interface* (*create)(Bridge < ::Test::I3_factory>*, Long, Interface*);
BRIDGE_END ()

template <class T>
class Client <T, ::Test::I3_factory> :
	public T
{
public:
	::Test::I3_var create (Long addendum);
};

template <class T>
::Test::I3_var Client <T, ::Test::I3_factory>::create (Long addendum)
{
	Environment _env;
	Bridge < ::Test::I3_factory>& _b (T::_get_bridge (_env));
	I_ret < ::Test::I3> _ret = (_b._epv ().epv.create) (&_b, addendum, &_env);
	_env.check ();
	return _ret;
}

}
}

namespace Test {

class I3_factory : public CORBA::Nirvana::ClientInterface <I3_factory, ::CORBA::Object>
{};

}

#endif
