#include "IOReference.idl"
#include "../DynamicServant.idl"

module CORBA {
module Internal {

native InterfaceMetadataPtr;
native InterfacePtr;

pseudo interface ProxyFactory
{
	readonly attribute InterfaceMetadataPtr metadata;
	InterfacePtr create_proxy (in IOReference target, in unsigned short interface_idx, out DynamicServant deleter);
};

};
};
