/// \file
/// Current
/// CORBA 3.0, Chapter 4

#ifndef CORBA_CURRENT_IDL_
#define CORBA_CURRENT_IDL_

module CORBA {

typeprefix CORBA "omg.org";

// interface for the Current object
local interface Current
{};

};

#endif // CORBA_CURRENT_IDL_
