// File: CORBA_NVList.idl
// CORBA 3.0, Chapter 7
#ifndef CORBA_NVLIST_IDL_
#define CORBA_NVLIST_IDL_

#include "TypeCode.idl"

module CORBA {

typeprefix CORBA "omg.org";

exception Bounds {};

pseudo interface NamedValue
{
  readonly attribute Identifier name;
  readonly attribute any value;
  readonly attribute Flags flags;
};

pseudo interface NVList
{
  readonly attribute unsigned long count;
  NamedValue add (in Flags flags);
  NamedValue add_item (in Identifier item_name, in Flags flags);
  NamedValue add_value (
    in Identifier item_name,
    in any val,
    in Flags flags
  );
  NamedValue item (in unsigned long index) raises (Bounds);
  void remove (in unsigned long index) raises (Bounds);
};

};

#endif // CORBA_NVLIST_IDL_
