/// \file
/// CORBA 3.0, Chapter 4
/// Reduced for now

#include "TypeCode.idl"

module CORBA {

#ifdef _PRE_3_0_COMPILER_
#pragma prefix "omg.org"
#else
typeprefix CORBA "omg.org";
#endif

native ValueFactory;

/// ORB
pseudo interface ORB
{
	typedef string ObjectId;
	typedef sequence <ObjectId> ObjectIdList;

	exception InvalidName{};

	/// Initial reference operation
	Object resolve_initial_references (
		in ObjectId identifier
	) raises (InvalidName);

  ValueFactory register_value_factory (
    in RepositoryId             id,
    in ValueFactory             _factory
  );

  void unregister_value_factory (
    in RepositoryId             id);

  ValueFactory lookup_value_factory (
    in RepositoryId             id);

};

};
