/// \file
/// CORBA 3.0, Chapter 4
/// Reduced for now

module CORBA {

#ifdef _PRE_3_0_COMPILER_
#pragma prefix "omg.org"
#else
typeprefix CORBA "omg.org";
#endif

/// ORB
pseudo interface ORB
{
	typedef string ObjectId;
	typedef sequence <ObjectId> ObjectIdList;

	exception InvalidName{};

	/// Initial reference operation
	Object resolve_initial_references (
		in ObjectId identifier
	) raises (InvalidName);

};

};
