/// \file
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/

module CORBA {
module Internal {

native NativeFloat;
native NativeDouble;
native NativeLongDouble;

native FloatIEEE4;
native FloatIEEE8;
native FloatIEEE16;

pseudo interface SFloat4
{
	typedef FloatIEEE4 FloatIEEE;

	void from_float (in NativeFloat x, out FloatIEEE f);
	void from_long (in long x, out FloatIEEE f);
	void from_unsigned_long (in unsigned long x, out FloatIEEE f);
	void from_long_long (in long long x, out FloatIEEE f);
	void from_unsigned_long_long (in unsigned long long x, out FloatIEEE f);

	void to_float (in FloatIEEE f, out NativeFloat x);
	long to_long (in FloatIEEE f);
	long long to_long_long (in FloatIEEE f);

	void add (inout FloatIEEE x, in FloatIEEE y);
	void sub (inout FloatIEEE x, in FloatIEEE y);
	void mul (inout FloatIEEE x, in FloatIEEE y);
	void div (inout FloatIEEE x, in FloatIEEE y);

	boolean eq (in FloatIEEE x, in FloatIEEE y);
	boolean le (in FloatIEEE x, in FloatIEEE y);
	boolean lt (in FloatIEEE x, in FloatIEEE y);
};

pseudo interface SFloat8
{
	typedef FloatIEEE8 FloatIEEE;

	void from_double (in NativeDouble x, out FloatIEEE f);
	void from_long (in long x, out FloatIEEE f);
	void from_unsigned_long (in unsigned long x, out FloatIEEE f);
	void from_long_long (in long long x, out FloatIEEE f);
	void from_unsigned_long_long (in unsigned long long x, out FloatIEEE f);

	void to_double (in FloatIEEE f, out NativeDouble x);
	long to_long (in FloatIEEE f);
	long long to_long_long (in FloatIEEE f);

	void add (inout FloatIEEE x, in FloatIEEE y);
	void sub (inout FloatIEEE x, in FloatIEEE y);
	void mul (inout FloatIEEE x, in FloatIEEE y);
	void div (inout FloatIEEE x, in FloatIEEE y);

	boolean eq (in FloatIEEE x, in FloatIEEE y);
	boolean le (in FloatIEEE x, in FloatIEEE y);
	boolean lt (in FloatIEEE x, in FloatIEEE y);
};

pseudo interface SFloat16
{
	typedef FloatIEEE16 FloatIEEE;

	void from_double (in NativeDouble x, out FloatIEEE f);
	void from_long_double (in NativeLongDouble x, out FloatIEEE f);
	void from_long (in long x, out FloatIEEE f);
	void from_unsigned_long (in unsigned long x, out FloatIEEE f);
	void from_long_long (in long long x, out FloatIEEE f);
	void from_unsigned_long_long (in unsigned long long x, out FloatIEEE f);

	void to_double (in FloatIEEE f, out NativeDouble x);
	void to_long_double (in FloatIEEE f, out NativeLongDouble x);
	long to_long (in FloatIEEE f);
	long long to_long_long (in FloatIEEE f);

	void add (inout FloatIEEE x, in FloatIEEE y);
	void sub (inout FloatIEEE x, in FloatIEEE y);
	void mul (inout FloatIEEE x, in FloatIEEE y);
	void div (inout FloatIEEE x, in FloatIEEE y);

	boolean eq (in FloatIEEE x, in FloatIEEE y);
	boolean le (in FloatIEEE x, in FloatIEEE y);
	boolean lt (in FloatIEEE x, in FloatIEEE y);
};

const SFloat4 g_sfloat4;
const SFloat8 g_sfloat8;
const SFloat16 g_sfloat16;

};
};
