/// \file
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
module CORBA{
module Internal {

native NativeFloat;
native NativeDouble;
native NativeLongDouble;

pseudo interface SFloat16
{
	struct IEEE
	{
		unsigned long long u0;
		unsigned long long u1;
	};

	void from_float (in NativeFloat x, out IEEE f);
	void from_double (in NativeDouble x, out IEEE f);
	void from_long_double (in NativeLongDouble x, out IEEE f);
	void from_long (in long x, out IEEE f);
	void from_unsigned_long (in unsigned long x, out IEEE f);
	void from_long_long (in long long x, out IEEE f);
	void from_unsigned_long_long (in unsigned long long x, out IEEE f);

	void to_float (in IEEE f, out NativeFloat x);
	void to_double (in IEEE f, out NativeDouble x);
	void to_long_double (in IEEE f, out NativeLongDouble x);
	void to_long (in IEEE f, out long x);
	void to_long_long (in IEEE f, out long long x);

	void plus (in IEEE x, in IEEE y, out IEEE f);
	void minus (in IEEE x, in IEEE y, out IEEE f);
	void mul (in IEEE x, in IEEE y, out IEEE f);
	void div (in IEEE x, in IEEE y, out IEEE f);
};

const SFloat16 g_sfloat16;

};
};
