/// \file
/*
* Nirvana IDL support library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2025 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
#ifndef NIRVANA_ORB_TRAITSINTERFACE_H_
#define NIRVANA_ORB_TRAITSINTERFACE_H_
#pragma once

#include "Type_interface.h"

namespace CORBA {
namespace Internal {

/// \brief Base for IDL::traits <> generated by the IDL compiler.
/// 
/// \typeparam Itf interface.
/// 
template <class Itf>
struct TraitsInterface
{
	using value_type = typename TypeItfBase <Itf>::Var;
	using ref_type = value_type;
	using ptr_type = I_ptr <Itf>;
	using in_type = ptr_type;
	using out_type = ref_type&;
	using inout_type = ref_type&;
};

}
}

#endif
